// Regenerates lib/src/models/display/display_icon_name.dart from
// tool/display_icons.json (Meta's DAT IconName catalog).
//
//   dart run tool/gen_icon_names.dart
//
// Update display_icons.json from the MWDATDisplay `.swiftinterface` (or the
// `display-icons` docs page) when a new DAT release adds icons.

// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

void main() {
  final json =
      jsonDecode(File('tool/display_icons.json').readAsStringSync())
          as Map<String, dynamic>;
  final icons = (json['icons'] as List<dynamic>).cast<String>();
  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_icon_names.dart from tool/display_icons.json.',
    )
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln(
      "/// Built-in icons of Meta's Display SDK (DAT 1.0, ${icons.length} icons).",
    )
    ..writeln('///')
    ..writeln(
      '/// The wire name is the iOS `IconName` case; Android maps it to the',
    )
    ..writeln('/// SCREAMING_SNAKE_CASE `IconName` constant.')
    ..writeln('enum DisplayIconName {');
  for (var i = 0; i < icons.length; i++) {
    final name = icons[i];
    out
      ..writeln('  /// The `$name` icon.')
      ..writeln("  $name('$name')${i == icons.length - 1 ? ';' : ','}");
    if (i != icons.length - 1) out.writeln();
  }
  out
    ..writeln()
    ..writeln('  const DisplayIconName(this.wireName);')
    ..writeln()
    ..writeln('  /// The string used on the platform channel.')
    ..writeln('  final String wireName;')
    ..writeln('}');
  File(
    'lib/src/models/display/display_icon_name.dart',
  ).writeAsStringSync(out.toString());
  print('Wrote ${icons.length} icons.');
}
