// GENERATED by tool/gen_icon_names.dart from tool/display_icons.json.
// Do not edit by hand.

/// Built-in icons of Meta's Display SDK (DAT 1.0, 116 icons).
///
/// The wire name is the iOS `IconName` case; Android maps it to the
/// SCREAMING_SNAKE_CASE `IconName` constant.
enum DisplayIconName {
  /// The `airplane` icon.
  airplane('airplane'),

  /// The `arrowDownShallowU` icon.
  arrowDownShallowU('arrowDownShallowU'),

  /// The `arrowLeft` icon.
  arrowLeft('arrowLeft'),

  /// The `arrowRight` icon.
  arrowRight('arrowRight'),

  /// The `arrowULeft` icon.
  arrowULeft('arrowULeft'),

  /// The `arrowUpShallowU` icon.
  arrowUpShallowU('arrowUpShallowU'),

  /// The `avatar` icon.
  avatar('avatar'),

  /// The `avatarOff` icon.
  avatarOff('avatarOff'),

  /// The `bedSide` icon.
  bedSide('bedSide'),

  /// The `bell` icon.
  bell('bell'),

  /// The `bellDiagonalRightDot` icon.
  bellDiagonalRightDot('bellDiagonalRightDot'),

  /// The `bellOff` icon.
  bellOff('bellOff'),

  /// The `bikeShare` icon.
  bikeShare('bikeShare'),

  /// The `bug` icon.
  bug('bug'),

  /// The `bullhorn` icon.
  bullhorn('bullhorn'),

  /// The `bus` icon.
  bus('bus'),

  /// The `calendar` icon.
  calendar('calendar'),

  /// The `campfire` icon.
  campfire('campfire'),

  /// The `caretDown` icon.
  caretDown('caretDown'),

  /// The `caretLeft` icon.
  caretLeft('caretLeft'),

  /// The `caretRight` icon.
  caretRight('caretRight'),

  /// The `caretUp` icon.
  caretUp('caretUp'),

  /// The `carFrontView` icon.
  carFrontView('carFrontView'),

  /// The `cart` icon.
  cart('cart'),

  /// The `checkmark` icon.
  checkmark('checkmark'),

  /// The `checkmarkCircle` icon.
  checkmarkCircle('checkmarkCircle'),

  /// The `circle8RaysLarge` icon.
  circle8RaysLarge('circle8RaysLarge'),

  /// The `circleHandle` icon.
  circleHandle('circleHandle'),

  /// The `clock` icon.
  clock('clock'),

  /// The `cloud` icon.
  cloud('cloud'),

  /// The `cloudCrescentMoon` icon.
  cloudCrescentMoon('cloudCrescentMoon'),

  /// The `cloudDotFourRays` icon.
  cloudDotFourRays('cloudDotFourRays'),

  /// The `cloudFiveDashes` icon.
  cloudFiveDashes('cloudFiveDashes'),

  /// The `cloudHookSwirl` icon.
  cloudHookSwirl('cloudHookSwirl'),

  /// The `cloudLightning` icon.
  cloudLightning('cloudLightning'),

  /// The `cocktailGlass` icon.
  cocktailGlass('cocktailGlass'),

  /// The `code` icon.
  code('code'),

  /// The `coffeeCup` icon.
  coffeeCup('coffeeCup'),

  /// The `compassNorthUpRed` icon.
  compassNorthUpRed('compassNorthUpRed'),

  /// The `containerWithLid` icon.
  containerWithLid('containerWithLid'),

  /// The `crossBriefcase` icon.
  crossBriefcase('crossBriefcase'),

  /// The `dropper` icon.
  dropper('dropper'),

  /// The `envelopeOpen` icon.
  envelopeOpen('envelopeOpen'),

  /// The `exclamationCircle` icon.
  exclamationCircle('exclamationCircle'),

  /// The `exclamationTriangle` icon.
  exclamationTriangle('exclamationTriangle'),

  /// The `eye` icon.
  eye('eye'),

  /// The `forkKnife` icon.
  forkKnife('forkKnife'),

  /// The `fourArcsUpFilled` icon.
  fourArcsUpFilled('fourArcsUpFilled'),

  /// The `fourArcsUpGrayscale` icon.
  fourArcsUpGrayscale('fourArcsUpGrayscale'),

  /// The `fourCornerFrame` icon.
  fourCornerFrame('fourCornerFrame'),

  /// The `gear` icon.
  gear('gear'),

  /// The `globeWesternHemisphere` icon.
  globeWesternHemisphere('globeWesternHemisphere'),

  /// The `graduationCap` icon.
  graduationCap('graduationCap'),

  /// The `hashtag` icon.
  hashtag('hashtag'),

  /// The `headphones` icon.
  headphones('headphones'),

  /// The `heart` icon.
  heart('heart'),

  /// The `house` icon.
  house('house'),

  /// The `iCircle` icon.
  iCircle('iCircle'),

  /// The `lightBulb` icon.
  lightBulb('lightBulb'),

  /// The `magicWand` icon.
  magicWand('magicWand'),

  /// The `metaAi` icon.
  metaAi('metaAi'),

  /// The `mountainSquare` icon.
  mountainSquare('mountainSquare'),

  /// The `mountainSquareStacked` icon.
  mountainSquareStacked('mountainSquareStacked'),

  /// The `museumBuilding` icon.
  museumBuilding('museumBuilding'),

  /// The `musicNote` icon.
  musicNote('musicNote'),

  /// The `nineSquaresGrid` icon.
  nineSquaresGrid('nineSquaresGrid'),

  /// The `padlockClosed` icon.
  padlockClosed('padlockClosed'),

  /// The `padlockOpen` icon.
  padlockOpen('padlockOpen'),

  /// The `palette` icon.
  palette('palette'),

  /// The `paperAirplane` icon.
  paperAirplane('paperAirplane'),

  /// The `pencil` icon.
  pencil('pencil'),

  /// The `pencilSquare` icon.
  pencilSquare('pencilSquare'),

  /// The `person` icon.
  person('person'),

  /// The `personCircle` icon.
  personCircle('personCircle'),

  /// The `phone` icon.
  phone('phone'),

  /// The `phoneHandsetArrowDownLeft` icon.
  phoneHandsetArrowDownLeft('phoneHandsetArrowDownLeft'),

  /// The `phoneHandsetArrowUpRight` icon.
  phoneHandsetArrowUpRight('phoneHandsetArrowUpRight'),

  /// The `phoneSlash` icon.
  phoneSlash('phoneSlash'),

  /// The `pizzaSlice` icon.
  pizzaSlice('pizzaSlice'),

  /// The `plus` icon.
  plus('plus'),

  /// The `plusCircle` icon.
  plusCircle('plusCircle'),

  /// The `shoppingBag` icon.
  shoppingBag('shoppingBag'),

  /// The `slidersHorizontal` icon.
  slidersHorizontal('slidersHorizontal'),

  /// The `smartGlasses` icon.
  smartGlasses('smartGlasses'),

  /// The `smileyCircle` icon.
  smileyCircle('smileyCircle'),

  /// The `speakerOff` icon.
  speakerOff('speakerOff'),

  /// The `speakerWithOneArc` icon.
  speakerWithOneArc('speakerWithOneArc'),

  /// The `speakerWithThreeArcs` icon.
  speakerWithThreeArcs('speakerWithThreeArcs'),

  /// The `speakerWithTwoArcs` icon.
  speakerWithTwoArcs('speakerWithTwoArcs'),

  /// The `speechBubble` icon.
  speechBubble('speechBubble'),

  /// The `speechBubbleOff` icon.
  speechBubbleOff('speechBubbleOff'),

  /// The `stadium` icon.
  stadium('stadium'),

  /// The `star` icon.
  star('star'),

  /// The `starCircleTriangleAi` icon.
  starCircleTriangleAi('starCircleTriangleAi'),

  /// The `taxi` icon.
  taxi('taxi'),

  /// The `threeDotsHorizontal` icon.
  threeDotsHorizontal('threeDotsHorizontal'),

  /// The `threeDotSpeechBubble` icon.
  threeDotSpeechBubble('threeDotSpeechBubble'),

  /// The `threeHorizontalLines` icon.
  threeHorizontalLines('threeHorizontalLines'),

  /// The `threeHorizontalLinesStackedDescending` icon.
  threeHorizontalLinesStackedDescending(
    'threeHorizontalLinesStackedDescending',
  ),

  /// The `threePeopleOverlapping` icon.
  threePeopleOverlapping('threePeopleOverlapping'),

  /// The `train` icon.
  train('train'),

  /// The `tree` icon.
  tree('tree'),

  /// The `triangleLeftVerticalLine` icon.
  triangleLeftVerticalLine('triangleLeftVerticalLine'),

  /// The `triangleRight` icon.
  triangleRight('triangleRight'),

  /// The `triangleRightCircle` icon.
  triangleRightCircle('triangleRightCircle'),

  /// The `triangleRightVerticalLine` icon.
  triangleRightVerticalLine('triangleRightVerticalLine'),

  /// The `twoArrowsClockwise` icon.
  twoArrowsClockwise('twoArrowsClockwise'),

  /// The `twoLinesParallel` icon.
  twoLinesParallel('twoLinesParallel'),

  /// The `twoSquaresStackedRightDown` icon.
  twoSquaresStackedRightDown('twoSquaresStackedRightDown'),

  /// The `twoTrianglesLeft` icon.
  twoTrianglesLeft('twoTrianglesLeft'),

  /// The `twoTrianglesRight` icon.
  twoTrianglesRight('twoTrianglesRight'),

  /// The `videoCamera` icon.
  videoCamera('videoCamera'),

  /// The `videoCameraOff` icon.
  videoCameraOff('videoCameraOff'),

  /// The `wristband` icon.
  wristband('wristband'),

  /// The `wristbandSlash` icon.
  wristbandSlash('wristbandSlash'),

  /// The `x` icon.
  x('x');

  const DisplayIconName(this.wireName);

  /// The string used on the platform channel.
  final String wireName;
}
